### ISSUE TITLE
ArchiveSpark 2

### ISSUE THREAD

**Issue by helgeho** [ibnesayeed/docker-archivespark#1]
Hi, a lot has happened since this this Docker image was built. There is now ArchiveSpark 2, which does not only support Web archives, but also books and any other data types with corresponding data specs. In addition to that, we have added many new operations, such as easy filter functions and exception handling, as well as a new group operator that creates groups of records, which are enrichable in itself.

So it would be great if you updated this Docker image to use the new ArchiveSpark as well. We provide another Docker image that's based on [Zeppelin](https://zeppelin.apache.org/) instead of [Jupyter](http://jupyter.org/), which you could use as a template for this: https://github.com/helgeho/ArchiveSpark-Zeppelin-Docker

Zeppelin has a built-in Spark kernel. For Jupyter you will need to update to the latest [Toree](https://github.com/apache/incubator-toree). Also we support Spark 2 now.

So please give the Zeppelin Docker image a try and see if you can make this one work similarly, that would be great! We are running ArchiveSpark 2 with Jupyter and Spark 2 on our cluster already (without Docker) and that works without any problems. So let me know if you need help or more information!

**Comment by ibnesayeed** [comment]
Hi @helgeho thanks for the heads up. I was wondering where is the new pre-built kernel of ArchiveSpark hosted now? Earlier there was a copy at http://l3s.de/~holzmann/archivespark-kernel.tar.gz from where this image was downloading it instead of building from the source.

**Comment by helgeho** [comment]
There you go: http://l3s.de/~holzmann/archivespark2-kernel.tar.gz
Remember to change the paths (Toree and Spark) in the kernel.json file. This one requires Spark 2.*.
Also the master in `SPARK_OPTS` needs to be set to local, it is probably a good idea to just copy the parameters from your current one. Also, it would be great if ArchiveSpark is being build as part of the Dockerfile, similar to how we do it in https://github.com/helgeho/ArchiveSpark-Zeppelin-Docker

Thanks a lot in advance!

**Comment by ibnesayeed** [comment]
Hi @helgeho, I was trying to update it with `spark-2.0.2-bin-hadoop2.7`, but getting the following error when I start the example notebook. Any insights?

```
[I 19:56:50.265 NotebookApp] KernelRestarter: restarting kernel (1/5)
Starting Spark Kernel with SPARK_HOME=/spark
Warning: Local jar /opt/cloudera/parcels/GPLEXTRAS/lib/hadoop/lib/hadoop-lzo.jar does not exist, skipping.
Exception in thread "main" java.lang.UnsupportedClassVersionError: com/typesafe/config/ConfigMergeable : Unsupported major.minor version 52.0
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:803)
    at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
    at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
    at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
    at org.apache.toree.Main$.delayedEndpoint$org$apache$toree$Main$1(Main.scala:25)
    at org.apache.toree.Main$delayedInit$body.apply(Main.scala:24)
    at scala.Function0$class.apply$mcV$sp(Function0.scala:34)
    at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
    at scala.App$$anonfun$main$1.apply(App.scala:76)
    at scala.App$$anonfun$main$1.apply(App.scala:76)
    at scala.collection.immutable.List.foreach(List.scala:381)
    at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:35)
    at scala.App$class.main(App.scala:76)
    at org.apache.toree.Main$.main(Main.scala:24)
    at org.apache.toree.Main.main(Main.scala)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:736)
    at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:185)
    at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:210)
    at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:124)
    at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
```

**Comment by helgeho** [comment]
I am sorry, that's actually my fault. I testes and packaged the kernel on our cluster and that's something specific to it. So I removed the dependency on the jar from the exception and repackaged it. Please download http://l3s.de/~holzmann/archivespark2-kernel.tar.gz again and replace your `toree` directory with the new one (the other files are unchanged).

**Comment by ibnesayeed** [comment]
The cloudera warning is gone, but the exception still exists.

```
[I 21:05:11.813 NotebookApp] KernelRestarter: restarting kernel (1/5)
Starting Spark Kernel with SPARK_HOME=/spark
Exception in thread "main" java.lang.UnsupportedClassVersionError: com/typesafe/config/ConfigMergeable : Unsupported major.minor version 52.0
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:803)
    at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
    at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
    at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
    at org.apache.toree.Main$.delayedEndpoint$org$apache$toree$Main$1(Main.scala:25)
    at org.apache.toree.Main$delayedInit$body.apply(Main.scala:24)
    at scala.Function0$class.apply$mcV$sp(Function0.scala:34)
    at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
    at scala.App$$anonfun$main$1.apply(App.scala:76)
    at scala.App$$anonfun$main$1.apply(App.scala:76)
    at scala.collection.immutable.List.foreach(List.scala:381)
    at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:35)
    at scala.App$class.main(App.scala:76)
    at org.apache.toree.Main$.main(Main.scala:24)
    at org.apache.toree.Main.main(Main.scala)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:736)
    at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:185)
    at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:210)
    at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:124)
    at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
```

**Comment by helgeho** [comment]
Hm, that's some incompatibility issue, are you using Java 1.8? If not, try to upgrade: https://github.com/helgeho/ArchiveSpark-Zeppelin-Docker/blob/master/Dockerfile#L13

**Comment by ibnesayeed** [comment]
Yeah, I was exploring along the same lines and was about to try that. In fact I was using `default-jre` which happens to be `1.7.0` version of Java. I am using JRE because building is done outside which makes the image smaller and more suitable for production.

**Comment by ibnesayeed** [comment]
Got it working, but existing example notebook file throws compile error when executed. Has anything changed they way things are imported?

**Comment by ibnesayeed** [comment]
All done! Updated the example notebook file according to the getting started documentation.

**Comment by ibnesayeed** [comment]
@helgeho I have tried [JupyterLab](https://github.com/jupyterlab/jupyterlab) locally. It took some time to get everything in place, but the end result was pleasant. I did not push the changes to GitHub even in an experimental branch though as JupyterLab is yet to reach the first beta release version.

Also, I have created a [PR](https://github.com/helgeho/ArchiveSpark-Zeppelin-Docker/pull/1) to the ArchiveSpark-Zeppelin-Docker repo to improve the quality of the Dockerfile and the resulting image. Please give it a try and if it looks satisfactory then feel free to accept the PR.
